#!/usr/bin/env bash

echo "DOTFILES! - Let's Rock It!"

# If this is used with -h or --help
if [[ "$1" == "-h" || "$1" == "--help" ]]; then cat <<HELP
Usage: $(basename "$0")

This file will install tomatao's .bashrc

No options necessary.

It will copy the dotfiles directory into ~/.dotfiles
It will run the scripts in the following directories:
- init

It will then do nothing :D DOTFILES!!!
HELP
exit; 
fi

#  TODO gitpull here!

pwd="$(dirname "$0")"


source "$pwd/bin/dotfiles_functions"
source "$pwd/bin/dotfiles_requirements"
source "$pwd/bin/dotfiles_sync"

cd ~/.dotfiles

# Add binaries to path
PATH=~/.dotfiles/bin:$PATH
export PATH


# Tweak file globbing.
shopt -s dotglob
shopt -s nullglob # make * eval to nothing if no files

# Run the installtion scripts in the following
e_header "Initializing!"
run_directory "init"


# Unset file globbing tweaks
shopt -u nullglob
unset new_dotfiles_install
unset pwd
unset run_directory

. ~/.profile

e_header "All done!"