[direnv]
disabled = false
format = '[$symbol $loaded$allowed]($style) '
symbol = ""
allowed_msg = ''
loaded_msg = '󰄭'
not_allowed_msg = ''
unloaded_msg = "not loaded"
style = "fg:color_purple"

[time]
disabled = false

[aws]
symbol = " "

[bun]
symbol = " "

[conda]
symbol = " "

[container]
symbol = "⬢ "

[deno]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[git_branch]
style = "fg:color_green"
symbol = " "

[git_status]
style = 'bold red'
format = '([\[$all_status$ahead_behind\]]($style) )'
ahead = '⇡$count'
diverged = '⇕⇡$ahead_count⇣$behind_count'
behind = '⇣$count'

[gleam]
symbol = "⭐ "

[golang]
symbol = " "

[haskell]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[jobs]
symbol = "✦ "

[memory_usage]
symbol = "󰍛 "

[nodejs]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[zig]
symbol = " "
