#!/usr/bin/env bash

# Might not be bash, e.g. `sh`. So, check for bash
if [ -n "$BASH_VERSION" ]; then
    # Share settings between login and interactive shells
    if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
    fi
fi
